### ISSUE TITLE
No !!leaderboard working

### ISSUE THREAD

**Issue by TeoNero** [g1ver/EFT-Teamkill-Tracker#1]
Hi,

The command "!!leaderboard" doesn't work anymore for tracking kills. It works for tracking deaths and to insert new teamkills. Thank you.

**Comment by g1ver** [comment]
Hello, thanks for reporting the issue. It seems to be working fine on my test server. Could you send some screenshots of the command you're trying to run and the bot's response?

**Comment by TeoNero** [comment]
Hey, 
first of all thank you a lot for your fast answer and for the effort in making this wonderful tool. I am attaching the photo of three commands I have just performed on the Discord server. As you can see just the last one is working
![leaderboard](https://user-images.githubusercontent.com/97238489/148401057-690fe2fc-2250-40df-90cd-be31db16fa9e.png)

Thank you a lot again!

**Comment by g1ver** [comment]
Thanks for the screenshots. I'm investigating it right now.

**Comment by g1ver** [comment]
Hi. I believe I figured out the issue and pushed a potential fix to the bot. Can you try running the commands again?

**Comment by TeoNero** [comment]
Hi g1ver, now everything seems to work perfectly! Again thank you for everything from all our community!

**Comment by g1ver** [comment]
No problem. Thanks again for reporting the issue.
