### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by Starkville24** [g1ver/EFT-Teamkill-Tracker#2]
I just did the new update but none of the commands work for me. They work for everyone else in the discord but not me (the owner)

**Comment by g1ver** [comment]
That's weird. Are you able to see the commands at all? Or are the commands unresponsive?

**Comment by Starkville24** [comment]
I can see them they are just unresponsive

**Comment by g1ver** [comment]
Interesting.. but other users can use the commands and they work?

**Comment by Starkville24** [comment]
Yep lol it seems like the only don't work for me

**Comment by Starkville24** [comment]
Wait jk I just checked again and they are working sorry lol

**Comment by g1ver** [comment]
I've never heard of that happening before. Do you mind sending me your Discord ID and your server's ID? You may also want to check your role permissions to make sure you have the permission called "Use Application Commands".

Here's instructions on getting your Discord ID:
https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
